version: '3.4'

services:
  interprocesscommunication:
    image: interprocesscommunication
    networks:
      ipc_network:
        ipv4_address: 172.31.255.254
    build:
      context: .
      dockerfile: Dockerfile
  serviceclnt:
    networks:
      ipc_network:
        ipv4_address: 172.31.255.253       
    build:
      context: .
      dockerfile: DockerfileClientService
networks:
  ipc_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/24
          gateway: 172.31.255.1
